import { addPublicationJsonLd } from '@starter-kit/utils/seo/addPublicationJsonLd';
import { getAutogeneratedPublicationOG } from '@starter-kit/utils/social/og';
import request from 'graphql-request';
import { GetStaticProps } from 'next';
import Head from 'next/head';
import { useState } from 'react';
import { Waypoint } from 'react-waypoint';
import { Container } from '../components/container';
import { AppProvider } from '../components/contexts/appContext';
import { Footer } from '../components/footer';
import { Layout } from '../components/layout';
import { MinimalPosts } from '../components/minimal-posts';
import { PersonalHeader } from '../components/personal-theme-header';
import {
	MorePostsByPublicationDocument,
	MorePostsByPublicationQuery,
	MorePostsByPublicationQueryVariables,
	PageInfoFragment,
	PostFragment,
	PostsByPublicationDocument,
	PostsByPublicationQuery,
	PostsByPublicationQueryVariables,
	PublicationFragment,
} from '../generated/graphql';
import { SuperMinimalPosts } from '../components/super-minimal-posts';
import Link from 'next/link';

const GQL_ENDPOINT = process.env.NEXT_PUBLIC_HASHNODE_GQL_ENDPOINT;

type Props = {
	publication: PublicationFragment;
	initialPosts: PostFragment[];
	initialPageInfo: PageInfoFragment;
};

export default function Index({ publication, initialPosts, initialPageInfo }: Props) {
	const [posts, setPosts] = useState<PostFragment[]>(initialPosts);
	const [pageInfo, setPageInfo] = useState<Props['initialPageInfo']>(initialPageInfo);
	const [loadedMore, setLoadedMore] = useState(false);

	const loadMore = async () => {
		const data = await request<MorePostsByPublicationQuery, MorePostsByPublicationQueryVariables>(
			GQL_ENDPOINT,
			MorePostsByPublicationDocument,
			{
				first: 20,
				host: process.env.NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST,
				after: pageInfo.endCursor,
			},
		);
		if (!data.publication) {
			return;
		}
		const newPosts = data.publication.posts.edges.map((edge) => edge.node);
		setPosts([...posts, ...newPosts]);
		setPageInfo(data.publication.posts.pageInfo);
		setLoadedMore(true);
	};
	return (
		<AppProvider publication={publication}>
			<Head>
				<title>{publication.title}</title>
				<meta
					name="description"
					content={
						publication.descriptionSEO || publication.title || `${publication.author.name}'s Blog`
					}
				/>
				<meta property="twitter:card" content="summary_large_image" />
				<meta property="twitter:title" content={publication.displayTitle || publication.title || 'Hashnode Blog Starter Kit'} />
				<meta property="twitter:description" content={publication.descriptionSEO || publication.title || `${publication.author.name}'s Blog`} />
				<meta
					property="og:image"
					content={publication.ogMetaData.image || getAutogeneratedPublicationOG(publication)}
				/>
				<meta
					property="twitter:image"
					content={publication.ogMetaData.image || getAutogeneratedPublicationOG(publication)}
				/>
				<link rel="stylesheet" href="https://hashnode-blog-bay.vercel.app/styles/index.css" />
				<script
					type="application/ld+json"
					dangerouslySetInnerHTML={{
						__html: JSON.stringify(addPublicationJsonLd(publication)),
					}}
				/>
				<style>{`
					body {
						line-height: 1.5;
						font-size: 16px;
						margin: 50px auto;
						max-width: 670px;
						padding: 0 16px;
					}
				`}</style>
			</Head>
			<div id="main" style={{ marginTop: '70px' }}>
				<nav>
					<Link href="/">home</Link>{'/ '}
					<Link href="/blog">blog</Link>{'/ '}
					{/* <Link href="/philosophy.html">philosophy</Link>{'/ '}
					<Link href="/research.html">research</Link>{'/ '} */}
					{/* <Link href="/projects.html">projects</Link>{'/ '} */}
				</nav>
				<header>
					<h1 style={{ fontSize: "25px", marginBottom: 0 }}>{publication.title}</h1>
					<p style={{ marginTop: 0 }}>
						thoughts, opinions, ideas and experiences
					</p>
				</header>
				{posts.length > 0 && <SuperMinimalPosts context="home" posts={posts} />}
				<footer>
					<details open>
						<summary>let&apos;s connect</summary>
						<nav>
							<a href="https://www.linkedin.com/in/bhaskarrijal" target="_blank" rel="noopener">linkedin</a>{'/ '}
							<a href="https://github.com/bhaskarrijal" target="_blank" rel="noopener">github</a>{'/ '}
							<a href="https://twitter.com/bhaskarijal" target="_blank" rel="noopener">twitter</a>{'/ '}
						</nav>
					</details>
					{/* <hr style={{ borderTop: '1px solid #ebebeb' }} />
					<div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginTop: '-10px' }}>
						<p style={{ fontSize: '12px' }}>
							bhaskar rijal &copy; 1999
						</p>
						<p style={{ fontSize: '12px', display: 'flex', gap: '5px', alignItems: 'center' }}>
							<span>open for collaborations</span>
							<svg stroke="currentColor" fill="none" strokeWidth="2" viewBox="0 0 24 24" strokeLinecap="round" strokeLinejoin="round" height="15px" width="15px" xmlns="http://www.w3.org/2000/svg">
								<path d="M12 4m-1 0a1 1 0 1 0 2 0a1 1 0 1 0 -2 0"></path>
								<path d="M4 12m-1 0a1 1 0 1 0 2 0a1 1 0 1 0 -2 0"></path>
								<path d="M20 12m-1 0a1 1 0 1 0 2 0a1 1 0 1 0 -2 0"></path>
								<path d="M12 20m-1 0a1 1 0 1 0 2 0a1 1 0 1 0 -2 0"></path>
								<path d="M5.5 5.5l3 3"></path>
								<path d="M15.5 15.5l3 3"></path>
								<path d="M18.5 5.5l-3 3"></path>
								<path d="M8.5 15.5l-3 3"></path>
							</svg>
						</p>
					</div> */}
				</footer>
			</div>
		</AppProvider>
	);
}

export const getStaticProps: GetStaticProps<Props> = async () => {
	const data = await request<PostsByPublicationQuery, PostsByPublicationQueryVariables>(
		GQL_ENDPOINT,
		PostsByPublicationDocument,
		{
			first: 20,
			host: process.env.NEXT_PUBLIC_HASHNODE_PUBLICATION_HOST,
		},
	);

	const publication = data.publication;
	if (!publication) {
		return {
			notFound: true,
		};
	}
	const initialPosts = (publication.posts.edges ?? []).map((edge) => edge.node);

	return {
		props: {
			publication,
			initialPosts,
			initialPageInfo: publication.posts.pageInfo,
		},
		revalidate: 1,
	};
};
